CREATE DATABASE IF NOT EXISTS library CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE library;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL, phone VARCHAR(255), membership_id VARCHAR(255) UNIQUE,
 role VARCHAR(32) NOT NULL DEFAULT 'MEMBER', status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS books (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255) NOT NULL, author VARCHAR(255) NOT NULL, isbn VARCHAR(255) NOT NULL UNIQUE,
 genre VARCHAR(255), description VARCHAR(3000), publisher VARCHAR(255), publication_year INT, total_copies INT NOT NULL, available_copies INT NOT NULL,
 cover_image_url VARCHAR(2048), archived BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS library_transactions (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, book_id BIGINT NOT NULL, member_id BIGINT NOT NULL, borrow_date DATE NOT NULL,
 due_date DATE NOT NULL, return_date DATE, status VARCHAR(32) NOT NULL, fine_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_transaction_book FOREIGN KEY (book_id) REFERENCES books(id),
 CONSTRAINT fk_transaction_member FOREIGN KEY (member_id) REFERENCES users(id), INDEX idx_transaction_member_status (member_id,status), INDEX idx_transaction_book_status (book_id,status)
);
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, title VARCHAR(255) NOT NULL, message VARCHAR(2000) NOT NULL,
 type VARCHAR(32) NOT NULL, is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX idx_notification_user_read (user_id,is_read)
);
CREATE TABLE IF NOT EXISTS notification_preferences (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL UNIQUE, email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
 due_date_notifications BOOLEAN NOT NULL DEFAULT TRUE, new_book_notifications BOOLEAN NOT NULL DEFAULT TRUE, overdue_notifications BOOLEAN NOT NULL DEFAULT TRUE,
 CONSTRAINT fk_preferences_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS password_reset_tokens (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE, expires_at TIMESTAMP NOT NULL, used_at TIMESTAMP NULL,
 CONSTRAINT fk_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX idx_reset_token (token_hash)
);
CREATE TABLE IF NOT EXISTS search_history (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT NOT NULL, search_query VARCHAR(255) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_search_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX idx_search_user_created (user_id,created_at)
);
