import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { api, messageOf } from '../services/api'
import { ArrowRight, Plus, Search, Trash2, X } from 'lucide-react'

export default function AdminMembersPage(){
 const [rows,setRows]=useState([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const {register,handleSubmit,reset}=useForm()
 const load=()=>api.get('/members',{params:{q}}).then(r=>setRows(r.data)).catch(e=>setError(messageOf(e)))
 useEffect(()=>{load()},[q])
 const save=async data=>{setBusy(true);setError('');try{await api.post('/members',data);setOpen(false);reset();load()}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 const disable=async m=>{if(confirm(`Disable ${m.name}'s account?`)){try{await api.delete(`/members/${m.id}`);load()}catch(e){setError(messageOf(e))}}}
 return <><div className="page-header"><div><div className="eyebrow">COMMUNITY DIRECTORY</div><h1>Members</h1><p>Manage member accounts and check current borrowing activity.</p></div><button className="btn btn-dark" onClick={()=>setOpen(true)}><Plus size={16}/> Add member</button></div>{error&&<div className="notice">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}<div className="catalog-toolbar"><div className="searchbox"><Search size={18}/><input placeholder="Search name, email, membership ID" value={q} onChange={e=>setQ(e.target.value)}/></div><span className="result-count">{rows.length} members</span></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>MEMBER</th><th>MEMBERSHIP ID</th><th>STATUS</th><th>BOOKS BORROWED</th><th>JOINED</th><th></th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td><div className="table-person"><span className="avatar tiny">{m.name[0]}</span><div><b>{m.name}</b><small className="table-sub">{m.email}</small></div></div></td><td>{m.membershipId}</td><td><span className={`status ${m.status.toLowerCase()}`}>{m.status}</span></td><td>{m.booksBorrowed}</td><td>{new Date(m.joined).toLocaleDateString()}</td><td>{m.status==='ACTIVE'&&<button className="text-link danger-text" onClick={()=>disable(m)}>Disable</button>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty-inline">No members found.</div>}</div></section>{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><div className="eyebrow">MEMBER RECORD</div><h2>Add a member</h2></div><button className="icon-btn" onClick={()=>setOpen(false)}><X/></button></div><form className="form-stack" onSubmit={handleSubmit(save)}><label>Full name<input {...register('name',{required:true})}/></label><label>Email address<input type="email" {...register('email',{required:true})}/></label><div className="form-row"><label>Phone<input {...register('phone',{required:true})}/></label><label>Membership ID<input {...register('membershipId',{required:true})}/></label></div><label>Temporary password<input type="password" minLength="10" {...register('password',{required:true,minLength:10})}/></label><small className="form-hint">The password is stored as a BCrypt hash. Ask the member to change it after sign-in.</small><button className="btn btn-dark btn-full" disabled={busy}>{busy?'Creating…':'Create member'} <ArrowRight size={16}/></button></form></div></div>}</>
}
