import { useCallback, useEffect, useState } from 'react'
import { AlertTriangle, Check, Clock3, ShieldCheck, Trash2, UserRoundCheck, X } from 'lucide-react'
import { api, messageOf } from '../services/api'
import '../admin.css'

export default function AdminPanel(){
 const [applications,setApplications]=useState([]),[counts,setCounts]=useState({total:0,members:0,librarians:0,otherAdmins:0}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setError('');try{const [apps,users]=await Promise.all([api.get('/admin/librarian-applications'),api.get('/admin/users/count')]);setApplications(apps.data);setCounts(users.data)}catch(e){setError(messageOf(e))}},[])
 useEffect(()=>{load()},[load])
 const decide=async(id,decision)=>{setBusy(true);setError('');setNotice('');try{await api.post(`/admin/librarian-applications/${id}/${decision}`);setNotice(decision==='approve'?'Librarian access approved.':'Application declined.');await load()}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 const clearUsers=async()=>{const confirmation=window.prompt(`This permanently deletes ${counts.total} account(s) other than your administrator account, along with their history and notifications. Type DELETE ALL USERS to continue.`);if(confirmation!=='DELETE ALL USERS')return;setBusy(true);setError('');setNotice('');try{const response=await api.delete('/admin/users',{data:{confirmation}});setNotice(`${response.data.deleted} account(s) deleted. Your administrator account remains.`);await load()}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 return <>
  <div className="page-header"><div><div className="eyebrow">SYSTEM CONTROL</div><h1>Administrator panel</h1><p>Review librarian access and manage registered accounts.</p></div><span className="admin-badge"><ShieldCheck size={16}/> Administrator only</span></div>
  {error&&<div className="notice">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}{notice&&<div className="notice success">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message"><X size={16}/></button></div>}
  <div className="stats-grid admin-counts"><div className="stat-card"><div className="stat-icon"><UserRoundCheck size={19}/></div><div className="stat-content"><span>Accounts to clear</span><strong>{counts.total}</strong><small>Members, librarians, and other admins</small></div></div><div className="stat-card"><div className="stat-icon"><Clock3 size={19}/></div><div className="stat-content"><span>Waiting for approval</span><strong>{applications.length}</strong><small>Librarian applications</small></div></div></div>
  <section className="panel admin-section"><div className="panel-heading"><div><h2>Librarian applications</h2><p>Applicants cannot sign in until you approve them.</p></div><button className="btn btn-outline btn-sm" onClick={load} disabled={busy}>Refresh</button></div>
   {applications.length?applications.map(app=><article className="admin-application" key={app.id}><div className="admin-applicant"><span className="avatar">{app.name?.[0]?.toUpperCase()||'L'}</span><div><b>{app.name}</b><small>{app.email}</small></div></div><div className="admin-app-meta"><span>ID {app.membershipId}</span><span>Applied {app.createdAt?new Date(app.createdAt).toLocaleDateString():'—'}</span></div><div className="admin-app-actions"><button className="btn btn-dark btn-sm" disabled={busy} onClick={()=>decide(app.id,'approve')}><Check size={15}/> Approve</button><button className="btn btn-outline btn-sm" disabled={busy} onClick={()=>decide(app.id,'reject')}><X size={15}/> Decline</button></div></article>):<div className="empty-inline">No librarian applications are waiting.</div>}
  </section>
  <section className="panel admin-danger-zone"><div className="danger-heading"><span><AlertTriangle size={18}/></span><div><h2>Clear registered accounts</h2><p>Delete every account except the administrator currently signed in.</p></div></div><div className="danger-details">This also removes each deleted account’s borrowing history, notifications, preferences, reset tokens, and search history. Active borrowed copies are returned to inventory. This cannot be undone.</div><button className="btn btn-danger" disabled={busy||counts.total===0} onClick={clearUsers}><Trash2 size={16}/> Delete all {counts.total} account(s)</button></section>
 </>
}
