import { useEffect, useState } from 'react'
import { api, messageOf } from '../services/api'
import { Bell, BookOpen, Check, Clock3, Mail, X } from 'lucide-react'

export default function AdminNotificationsPage(){
 const [members,setMembers]=useState([]),[items,setItems]=useState([]),[selected,setSelected]=useState([]),[error,setError]=useState(''),[sent,setSent]=useState(''),[form,setForm]=useState({title:'',message:'',type:'SYSTEM'})
 const load=()=>api.get('/notifications').then(r=>setItems(r.data.items)).catch(e=>setError(messageOf(e)))
 useEffect(()=>{load();api.get('/members').then(r=>setMembers(r.data)).catch(e=>setError(messageOf(e)))},[])
 const send=async e=>{e.preventDefault();setError('');try{const r=await api.post('/notifications/send',{...form,recipientIds:selected});setSent(`Notice sent to ${r.data.sent} member${r.data.sent===1?'':'s'}.`);setForm({title:'',message:'',type:'SYSTEM'});setSelected([])}catch(e){setError(messageOf(e))}}
 const toggle=id=>setSelected(s=>s.includes(String(id))?s.filter(x=>x!==String(id)):[...s,String(id)])
 return <><div className="page-header"><div><div className="eyebrow">MEMBER COMMUNICATION</div><h1>Notifications</h1><p>Send library updates to everyone or choose specific members.</p></div></div>{error&&<div className="notice">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}{sent&&<div className="notice success">{sent}<button onClick={()=>setSent('')}><X size={16}/></button></div>}<div className="admin-notice-grid"><section className="panel send-panel"><div className="panel-heading"><div><h2>Compose announcement</h2><p>Members receive an in-app notice and eligible emails.</p></div></div><form className="form-stack" onSubmit={send}><label>Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Message<textarea required rows="4" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><label>Notification type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="SYSTEM">System update</option><option value="NEW_BOOK">New book</option><option value="DUE_DATE">Due date</option><option value="OVERDUE">Overdue</option></select></label><label>Recipients <small className="form-hint">Leave all unchecked to notify every member.</small></label><div className="recipient-list">{members.map(m=><label key={m.id} className="recipient-choice"><input type="checkbox" checked={selected.includes(String(m.id))} onChange={()=>toggle(m.id)}/><span>{m.name}<small>{m.membershipId}</small></span></label>)}{!members.length&&<span className="form-hint">No member accounts found.</span>}</div><button className="btn btn-dark">Send notification <Mail size={15}/></button></form></section><section className="panel notification-panel"><div className="panel-heading"><div><h2>Recent notices</h2><p>Recent updates sent to your librarian account</p></div></div>{items.length?items.map(n=><div className="notification-row" key={n.id}><span className={`notification-icon ${n.type.toLowerCase()}`}>{n.type==='NEW_BOOK'?<BookOpen size={18}/>:n.type==='OVERDUE'?<Clock3 size={18}/>:<Bell size={18}/>}</span><div><b>{n.title}</b><p>{n.message}</p><small><Clock3 size={13}/> {new Date(n.createdAt).toLocaleString()}</small></div>{n.read&&<Check size={15}/>}</div>):<div className="empty-inline">No recent notifications.</div>}</section></div></>
}
